version: '3'

volumes:
  data:

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgresdb_scoreboard
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: postgres
